<?php
namespace Mr;

use Illuminate\Database\Eloquent\Model;

class Machine extends Model
{
    protected $table = 'machine';

    protected $fillable
        = [
            'hostname',
            'machine_model',
            'machine_desc',
            'img_url',
            'cpu',
            'current_processor_speed',
            'cpu_arch',
            'os_version',
            'physical_memory',
            'platform_UUID',
            'number_processors',
            'SMC_version_system',
            'boot_rom_version',
            'bus_speed',
            'computer_name',
            'l2_cache',
            'machine_name',
            'packages',
            'buildversion'
        ];

    public function getRouteKeyName()
    {
        return 'serial_number';
    }

    //// RELATIONSHIPS

    /**
     * Get events generated by this machine
     */
    public function events()
    {
        return $this->hasMany('Mr\Event', 'serial_number', 'serial_number');
    }

    /**
     * Get report data submitted by this machine
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function reportData()
    {
        return $this->hasOne('Mr\ReportData', 'serial_number', 'serial_number');
    }

    /**
     * Get comment(s) associated with this machine
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comment()
    {
        return $this->hasMany('Mr\Comment', 'serial_number', 'serial_number');
    }

    /**
     * Get MachineGroup key/value rows associated with this machine through the `report_data` table.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
     */
    public function machineGroupKeyVals()
    {
        return $this->hasManyThrough(
            'Mr\MachineGroup',
            'Mr\ReportData', 
            'serial_number',
            'groupid',
            'serial_number'
        );
    }

    //// SCOPES
    
}